In [195]:
import pandas as pd
import openpyxl
import os
import glob, re

In [196]:
def read_excel(files):
    dfs = []
    for file in files:
        data = pd.read_excel(file, sheet_name='errors', index_col=0)
        name = os.path.splitext(os.path.basename(file))[0]
        data['model'] = name
        dfs.append(data)
        df = pd.concat(dfs,ignore_index=True)
    return df

In [197]:
def arrange_data(df, error):
    df = df.pivot(index='model', columns='error', values=error)
    return df

In [198]:
def min_vals(df, error):
    df1 = df.apply(lambda x: pd.Series({'model':x.idxmin(), error:x.min()})).T
    return df1

In [199]:
path = "model_Fe_Si_B_260311/**/test_res/*_test.xlsx"

In [200]:
files = glob.glob(path, recursive=True)

In [201]:
df = read_excel(files)
#df

In [202]:
#df.loc[df['model']=='model_rnd_e_matpes_lr0.0001_40_10_test']

In [206]:
rmse = arrange_data(df, 'rmse')
mae = arrange_data(df, 'mae')
rmse

error,test_energy,test_force,train_energy,train_force
model,,,,
model_rnd_e_matpes_lr0.0001_40_10_test,49.126072,0.162873,103.295626,0.152998
model_rnd_e_matpes_lr0.0001_60_10_test,46.366162,0.160293,102.324352,0.146102
model_rnd_e_scmace_lr0.0001_50_10_test,235.787810,0.553489,242.202670,0.409217
model_rnd_e_scmace_lr0.0001_70_10_test,217.728320,0.488373,220.058253,0.361185
model_rnd_e_scmace_lr0.0005_35_10_1.0_10.0_test,158.349821,0.397015,163.823864,0.297497
model_rnd_e_scmace_lr0.0005_35_10_1.0_20.0_test,158.627201,0.382897,162.241762,0.288744
model_rnd_e_scmace_lr0.0005_35_10_test,137.508214,0.361392,147.172804,0.269199
model_rnd_e_scmace_lr0.0005_40_10_test,125.988943,0.343971,143.041397,0.259032
model_rnd_e_scmace_lr0.0005_50_10_test,118.481997,0.326544,135.912583,0.249422
model_rnd_e_scmace_lr0.0005_70_10_test,102.238612,0.308716,126.602898,0.237873
model_rnd_e_scmace_swa_lr0.0001_100_10_test,210.180375,0.473279,212.670122,0.350139
model_rnd_e_scmace_swa_lr0.0001_70_10_test,237.027195,0.550759,242.469683,0.406412
model_test_matpes_lr0.0001_40_10_test,100.198900,0.141840,99.322695,0.155058
model_test_scmace_lr0.0005_40_10_test,285.102710,0.235741,100.576359,0.262232

In [204]:
min_vals(rmse, 'rsme')

                                               model       rsme
error
test_energy   model_rnd_e_matpes_lr0.0001_60_10_test  46.366162
test_force     model_test_matpes_lr0.0001_40_10_test    0.14184
train_energy   model_test_matpes_lr0.0001_40_10_test  99.322695
train_force   model_rnd_e_matpes_lr0.0001_60_10_test   0.146102

In [205]:
min_vals(mae, 'mae')

                                               model        mae
error
test_energy   model_rnd_e_matpes_lr0.0001_40_10_test  28.338427
test_force     model_test_matpes_lr0.0001_40_10_test   0.109191
train_energy   model_test_matpes_lr0.0001_40_10_test  20.340578
train_force   model_rnd_e_matpes_lr0.0001_60_10_test   0.111942

In [207]:
df.loc[df['model']=='model_rnd_e_matpes_lr0.0001_60_10_test']

,error,rmse,mae,r2,model
20,test_energy,46.366162,30.922178,0.988339,model_rnd_e_matpes_lr0.0001_60_10_test
21,train_energy,102.324352,31.753122,0.948945,model_rnd_e_matpes_lr0.0001_60_10_test
22,test_force,0.160293,0.120646,0.996712,model_rnd_e_matpes_lr0.0001_60_10_test
23,train_force,0.146102,0.111942,0.997242,model_rnd_e_matpes_lr0.0001_60_10_test