In [149]:
import pandas as pd
import openpyxl
import os
import glob, re

In [150]:
def read_excel(files):
    dfs = []
    for file in files:
        data = pd.read_excel(file, sheet_name='errors', index_col=0)
        name = os.path.splitext(os.path.basename(file))[0]
        data['model'] = name
        dfs.append(data)
        df = pd.concat(dfs,ignore_index=True)
    return df

In [151]:
def arrange_data(df, error):
    df = df.pivot(index='model', columns='error', values=error)
    return df

In [152]:
def min_vals(df):
    df1 = df.apply(lambda x: pd.Series({'model':x.idxmin(), 'rmse':x.min()})).T
    return df1

In [153]:
files = glob.glob("model_Fe_Si_B_260311/**/test_res/*_test.xlsx", recursive=True)

In [154]:
df = read_excel(files)
df

,error,rmse,mae,r2,model
0,test_energy,118.481997,71.653737,0.923852,model_rnd_e_scmace_lr0.0005_50_10_test
1,train_energy,135.912583,58.020711,0.909926,model_rnd_e_scmace_lr0.0005_50_10_test
2,test_force,0.326544,0.194564,0.986357,model_rnd_e_scmace_lr0.0005_50_10_test
3,train_force,0.249422,0.192764,0.991962,model_rnd_e_scmace_lr0.0005_50_10_test
4,test_energy,217.728320,127.244964,0.742853,model_rnd_e_scmace_lr0.0001_70_10_test
5,train_energy,220.058253,106.759566,0.763867,model_rnd_e_scmace_lr0.0001_70_10_test
6,test_force,0.488373,0.273879,0.969483,model_rnd_e_scmace_lr0.0001_70_10_test
7,train_force,0.361185,0.271666,0.983144,model_rnd_e_scmace_lr0.0001_70_10_test
8,test_energy,158.627201,107.242048,0.863508,model_rnd_e_scmace_lr0.0005_35_10_1.0_20.0_test
9,train_energy,162.241762,89.048684,0.871647,model_rnd_e_scmace_lr0.0005_35_10_1.0_20.0_test
10,test_force,0.382897,0.225899,0.981241,model_rnd_e_scmace_lr0.0005_35_10_1.0_20.0_test
11,train_force,0.288744,0.223246,0.989227,model_rnd_e_scmace_lr0.0005_35_10_1.0_20.0_test
12,test_energy,49.126072,28.338427,0.986909,model_rnd_e_matpes_lr0.0001_40_10_test
13,train_energy,103.295626,27.930106,0.947971,model_rnd_e_matpes_lr0.0001_40_10_test
14,test_force,0.162873,0.122402,0.996606,model_rnd_e_matpes_lr0.0001_40_10_test
15,train_force,0.152998,0.116890,0.996975,model_rnd_e_matpes_lr0.0001_40_10_test
16,test_energy,100.198900,98.103337,0.922826,model_test_matpes_lr0.0001_40_10_test
17,train_energy,99.322695,20.340578,0.954363,model_test_matpes_lr0.0001_40_10_test
18,test_force,0.141840,0.109191,0.988019,model_test_matpes_lr0.0001_40_10_test
19,train_force,0.155058,0.118735,0.997106,model_test_matpes_lr0.0001_40_10_test
20,test_energy,125.988943,92.850639,0.913897,model_rnd_e_scmace_lr0.0005_40_10_test
21,train_energy,143.041397,82.065096,0.900229,model_rnd_e_scmace_lr0.0005_40_10_test
22,test_force,0.343971,0.202344,0.984862,model_rnd_e_scmace_lr0.0005_40_10_test
23,train_force,0.259032,0.200300,0.991330,model_rnd_e_scmace_lr0.0005_40_10_test
24,test_energy,285.102710,275.496875,0.375189,model_test_scmace_lr0.0005_40_10_test
25,train_energy,100.576359,33.949621,0.953203,model_test_scmace_lr0.0005_40_10_test
26,test_force,0.235741,0.182746,0.966904,model_test_scmace_lr0.0005_40_10_test
27,train_force,0.262232,0.200913,0.991721,model_test_scmace_lr0.0005_40_10_test
28,test_energy,102.238612,66.424912,0.943300,model_rnd_e_scmace_lr0.0005_70_10_test
29,train_energy,126.602898,55.778623,0.921843,model_rnd_e_scmace_lr0.0005_70_10_test
30,test_force,0.308716,0.185798,0.987806,model_rnd_e_scmace_lr0.0005_70_10_test
31,train_force,0.237873,0.183532,0.992689,model_rnd_e_scmace_lr0.0005_70_10_test
32,test_energy,235.787810,140.733865,0.698426,model_rnd_e_scmace_lr0.0001_50_10_test
33,train_energy,242.202670,121.663693,0.713952,model_rnd_e_scmace_lr0.0001_50_10_test
34,test_force,0.553489,0.306007,0.960803,model_rnd_e_scmace_lr0.0001_50_10_test
35,train_force,0.409217,0.304171,0.978362,model_rnd_e_scmace_lr0.0001_50_10_test
36,test_energy,237.027195,142.010688,0.695247,model_rnd_e_scmace_swa_lr0.0001_70_10_test
37,train_energy,242.469683,122.911134,0.713321,model_rnd_e_scmace_swa_lr0.0001_70_10_test
38,test_force,0.550759,0.304697,0.961188,model_rnd_e_scmace_swa_lr0.0001_70_10_test
39,train_force,0.406412,0.302612,0.978658,model_rnd_e_scmace_swa_lr0.0001_70_10_test
40,test_energy,158.349821,115.157057,0.863985,model_rnd_e_scmace_lr0.0005_35_10_1.0_10.0_test
41,train_energy,163.823864,98.700222,0.869131,model_rnd_e_scmace_lr0.0005_35_10_1.0_10.0_test
42,test_force,0.397015,0.232842,0.979832,model_rnd_e_scmace_lr0.0005_35_10_1.0_10.0_test
43,train_force,0.297497,0.229834,0.988564,model_rnd_e_scmace_lr0.0005_35_10_1.0_10.0_test
44,test_energy,137.508214,83.874506,0.897433,model_rnd_e_scmace_lr0.0005_35_10_test
45,train_energy,147.172804,67.485662,0.894382,model_rnd_e_scmace_lr0.0005_35_10_test
46,test_force,0.361392,0.210334,0.983289,model_rnd_e_scmace_lr0.0005_35_10_test
47,train_force,0.269199,0.208131,0.990636,model_rnd_e_scmace_lr0.0005_35_10_test

In [155]:
df.loc[df['model']=='model_rnd_e_matpes_lr0.0001_40_10_test']

,error,rmse,mae,r2,model
12,test_energy,49.126072,28.338427,0.986909,model_rnd_e_matpes_lr0.0001_40_10_test
13,train_energy,103.295626,27.930106,0.947971,model_rnd_e_matpes_lr0.0001_40_10_test
14,test_force,0.162873,0.122402,0.996606,model_rnd_e_matpes_lr0.0001_40_10_test
15,train_force,0.152998,0.116890,0.996975,model_rnd_e_matpes_lr0.0001_40_10_test

In [156]:
rmse = arrange_data(df, 'rmse')
mae = arrange_data(df, 'mae')
#rmse

In [157]:
min_vals(rmse)

                                               model       rmse
error
test_energy   model_rnd_e_matpes_lr0.0001_40_10_test  49.126072
test_force     model_test_matpes_lr0.0001_40_10_test    0.14184
train_energy   model_test_matpes_lr0.0001_40_10_test  99.322695
train_force   model_rnd_e_matpes_lr0.0001_40_10_test   0.152998

In [158]:
min_vals(mae)

                                               model       rmse
error
test_energy   model_rnd_e_matpes_lr0.0001_40_10_test  28.338427
test_force     model_test_matpes_lr0.0001_40_10_test   0.109191
train_energy   model_test_matpes_lr0.0001_40_10_test  20.340578
train_force   model_rnd_e_matpes_lr0.0001_40_10_test    0.11689